export const SET_ALERT='SET_ALERT';
export const REMOVE_ALERT='REMOVE_ALERT';
export const REGISTER_SUCCESS='REGISTER_SUCCESS';
export const REGISTER_FAIL='REGISTER_FAIL';
export const USER_LOADED='USER_LOADED';
export const AUTH_ERROR='AUTH_ERROR';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAIL='LOGIN_FAIL';
export const LOGOUT_SUCCESS='LOGOUT_SUCCESS';
export const CARADD_SUCCESS='CARADD_SUCCESS'
export const CARADD_FAIL='CARADD_FAIL'
export const GET_PROFILE='GET_PROFILE'
export const CHANGEP_SUCCESS='CHANGEP_SUCCESS'
export const CHANGEP_FAIL='CHANGEP_FAIL'
export const PROFILE_ERR='PROFILE_ERR'

export const CARSLOAD_SUCC='CARSLOAD_SUCC'
export const CARSLOAD_FAIL='CARSLOAD_FAIL'

export const CARLOAD_SUCC='CARLOAD_SUCC'
export const CARLOAD_FAIL='CARLOAD_FAIL'
export const CARRENT_SUCC='CARRENT_SUCC'
export const CARRENT_FAIL='CARRENT_FAIL'
export const CARRENTUSER_SUCC='CARRENTUSER_SUCC'
export const CARRENTUSER_FAIL='CARRENTUSER_FAIL'

export const UPDATE_LIKES='UPDATE_LIKES'
export const CARUNRENTUSER_SUCC='CARUNRENTUSER_SUCC'
export const CARUNRENTUSER_FAIL='CARRENTUSER_FAIL'